TrajectoryPlannerROS:  
  max_vel_x: 0.14
  min_vel_x: 0.08
  min_in_place_vel_theta: 0.40
  max_vel_theta: 1.0  
  acc_lim_theta: 3.2  
  acc_lim_x: 2.5
  acc_lim_y: 2.5  
 
  holonomic_robot: false
  meter_scoring: true

